resolver: lts-14.7
allow-newer: true
packages:
  - node

extra-deps:
  - ../arivi-core/utils
  - ../arivi-core/crypto
  - ../arivi-core/p2p
  - ../arivi-core/network
  - ../xoken-core/core
  - ../xcql
  - serialise-0.2.0.0
  - cborg-0.2.0.0
  - timers-updatable-0.2.0.2
  - statsd-client-0.3.0.0
  - time-units-1.0.0
  - digest-pure-0.0.3
  - DRBG-0.5.5
  - stm-containers-1.0.1
  - either-unwrap-1.1
  - raaz-0.2.1
  - network-2.8.0.1
  - queue-0.1.2
  - stm-hamt-1.1.2
  - primitive-0.6.4.0
  - primitive-extras-0.6.6
  - deferred-folds-0.6.12
  - focus-1
  - tinylog-0.15.0
  - streamly-0.7.0
  - hasbolt-0.1.4.3
  - resource-pool-0.2.3.2
  - hashtables-1.2.3.4
  - yaml-0.11.1.2
  - vformat-0.14.1.0
  - daemons-0.3.0
  - snap-1.1.3.0
  - heist-1.1.0.1
  - map-syntax-0.3
  - pwstore-fast-2.4.4
  - xmlhtml-0.2.5.2
  - concurrent-hashtable-0.1.8
  - lens-4.19.2
  - git: https://github.com/xoken/snap-server.git
    commit: 20d4a32b9da8c927230016b76185dff223b3907e
