resolver: lts-14.7
allow-newer: true
packages:
    - node


extra-deps:

    - ../arivi-core/utils
    - ../arivi-core/crypto
    - ../arivi-core/p2p
    - ../arivi-core/network
    - ../xoken-core/core
    - serialise-0.2.0.0
    - cborg-0.2.0.0
    - timers-updatable-0.2.0.2
    - statsd-client-0.3.0.0
    - time-units-1.0.0
    - digest-pure-0.0.3
    - DRBG-0.5.5
    - stm-containers-1.0.1
    - either-unwrap-1.1
    - raaz-0.2.1
    - network-2.8.0.1
    - queue-0.1.2
    - stm-hamt-1.1.2
    - primitive-0.6.4.0
    - primitive-extras-0.6.6
    - deferred-folds-0.6.12
    - focus-1
    - cql-io-1.1.1
    - tinylog-0.15.0
    - streamly-0.7.0
    - hasbolt-0.1.3.6
    - resource-pool-0.2.3.2
    - cql-4.0.2
    - hashtables-1.2.3.4
